language: node_js
node_js:
  - 12

services:
  - docker

install:
  - echo "N/A"

before_script:
  - echo "TBD"

script:
  - docker --version
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag reverseproxy junglebadger/reverseproxy:v1
  - docker tag udagram-api-feed junglebadger/udagram-api-feed:v1
  - docker tag udagram-api-user junglebadger/udagram-api-user:v1
  - docker tag udagram-frontend junglebadger/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push junglebadger/reverseproxy:v1
  - docker push junglebadger/udagram-api-feed:v1
  - docker push junglebadger/udagram-api-user:v1
  - docker push junglebadger/udagram-frontend:v1