apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  selector:
    matchLabels:
      service: frontend
  replicas: 2
  template:
    metadata:
      labels:
        service: frontend
        api: external        
    spec:
      containers:
      - image: junglebadger/udagram-frontend:v7
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "16Mi"
            cpu: "65m"
          limits:
            memory: "256Mi"
            cpu: "125m"               
      restartPolicy: Always
